api:
  api_key: null  # will be loaded from .env
  base_url: "https://www.alphavantage.co/query?"
  symbols: ["IBM"]
  interval: "5min"

kafka:
  bootstrap_server: "localhost:9092"
  kafka_topic: "stock-data-stream"
  acks: "all"

aws:
  access_key_id: null
  secret_access_key: null
  region: "us-east-1"
  s3_src_bucket: "base10-kafka-stockstreaming-us-east-1-raw"
  s3_src_prefix: "intraday_data"
  s3_trgt_bucket: "pro11-stockstreaming-us-east-1-analytics"
  s3_trgt_prefix: ""